#---------------------------------------------------------
# NametagEdit by sgtcaze and Cory, updated for PaperMC 1.21+
#---------------------------------------------------------
# Development Builds: https://ci.nametagedit.com
# Source Code: http://www.github.com/sgtcaze/NametagEdit
#---------------------------------------------------------
#
# These settings allow you to customize the behavior of the
# tab list.
Tablist:
  Enabled: true
  LongTags: false

# If enabled, this plugin will send small data to MCStats.org.
MetricsEnabled: true

# If enabled, players with NametagEdit nametags will not be able to push each other (1.9+)
DisablePush: false

# Clears empty teams at an interval (seconds). -1 disables.
ClearEmptyTeamsInterval: -1

# Debug mode for verbose logs (/nte debug to toggle)
Debug: false

# Refresh nametag on world change (for multiworld servers)
RefreshTagOnWorldChange: false

# Interval (seconds) to refresh all nametags. 0 disables.
RefreshInterval: 0

# MySQL database support. Enable for database storage.
MySQL:
  Enabled: false
  Hostname: localhost
  Port: 3306
  Username: myUsername
  Password: myPassword
  Database: myDatabase
  GroupsTable: nametagedit_groups
  PlayersTable: nametagedit_players
  ConfigTable: nametagedit_config
  MinimumPoolSize: 10