name: NametagEdit
main: com.nametagedit.plugin.NametagEdit
version: ${project.version}
api-version: 1.21
authors: [sgtcaze, Cory, Lorenzo0111, Aurelien30000, bsmokovitz]
softdepend: [zPermissions, PermissionsEX, GroupManager, LuckPerms, LibsDisguises, Guilds, PlaceholderAPI]

commands:
  ne:
    description: NametagEdit commands
    aliases: [nte, nametagedit]